In [ ]:
battery_data = [[0,32,400,20,95],
                [1,35,395,22,88],
                [2,38,390,25,80],
                [3,40,385,28,70],
                [4,42,380,30,60],
                [5,45,375,32,48]]
for reading in battery_data:
  print(f"Time: {reading[0]}h, "
  f"Temperature: {reading[1]}C, "
  f"Voltage: {reading[2]}V, "
  f"Current: {reading[3]}A, "
  f"Charge: {reading[4]}%")

Time: 0h, Temperature: 32C, Voltage: 400V, Current: 20A, Charge: 95%
Time: 1h, Temperature: 35C, Voltage: 395V, Current: 22A, Charge: 88%
Time: 2h, Temperature: 38C, Voltage: 390V, Current: 25A, Charge: 80%
Time: 3h, Temperature: 40C, Voltage: 385V, Current: 28A, Charge: 70%
Time: 4h, Temperature: 42C, Voltage: 380V, Current: 30A, Charge: 60%
Time: 5h, Temperature: 45C, Voltage: 375V, Current: 32A, Charge: 48%


In [ ]:
for reading in battery_data:
  temperature = reading[1]
  if temperature > 40:
    print(f"Time {reading[0]}h : Hight Temperature Alert")
  else:
    print(f"Time {reading[0]}h : Temperature Normal")

Time 0h : Temperature Normal
Time 1h : Temperature Normal
Time 2h : Temperature Normal
Time 3h : Temperature Normal
Time 4h : Hight Temperature Alert
Time 5h : Hight Temperature Alert


In [ ]:
for reading in battery_data:
  charge = reading[4]
  if charge < 50:
    print(f"Time {reading[0]}h : Low Battery Alert")
  else:
    print(f"Time {reading[0]}h : Battery Charge Normal")

Time 0h : Battery Charge Normal
Time 1h : Battery Charge Normal
Time 2h : Battery Charge Normal
Time 3h : Battery Charge Normal
Time 4h : Battery Charge Normal
Time 5h : Low Battery Alert


In [ ]:
def battery_status(charge):
  if charge>70:
    return "High"
  elif 50<=charge<=70:
    return "Medium"
  else:
    return "Low"
for reading in battery_data:
  print(f"Time {reading[0]}h : "
  f"Charge = {reading[4]}%, "
  f"Status = {battery_status(reading[4])}")

Time 0h : Charge = 95%, Status = High
Time 1h : Charge = 88%, Status = High
Time 2h : Charge = 80%, Status = High
Time 3h : Charge = 70%, Status = Medium
Time 4h : Charge = 60%, Status = Medium
Time 5h : Charge = 48%, Status = Low


In [ ]:
import numpy as np
D = np.array([[32,400,20,95],
             [35,395,22,88],
             [38,390,25,80],
             [40,385,28,70],
             [42,380,30,60],
             [45,375,32,48]])
print(D.shape)

(6, 4)


In [ ]:
averages = np.mean(D,axis =0)
print("Average Temperature:",averages[0])
print("Average Voltage:",averages[1])
print("Average Current:",averages[2])
print("Average Charge:",averages[3])

Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


In [ ]:
temperatures = D[:,0]
print("Maximum Temperature:",np.max(temperatures))
print("Minimum Temperature:",np.min(temperatures))

Maximum Temperature: 45
Minimum Temperature: 32


In [ ]:
voltage = D[:,1]
print(voltage)

[400 395 390 385 380 375]


In [ ]:
high_temperature = D[D[:,0] > 40]
print(high_temperature)

[[ 42 380  30  60]
 [ 45 375  32  48]]


In [ ]:
low_battery = D[D[:,3] < 50]
print(low_battery)

[[ 45 375  32  48]]


In [ ]:
A = np.array([[2,1],[1,3]])
X = np.array([[40],[25]])
Y = A @ X
print(Y)

[[105]
 [115]]


In [ ]:
print(A.T)

[[2 1]
 [1 3]]


In [ ]:
print( np.linalg.det(A))

5.000000000000001


In [ ]:
print(np.linalg.inv(A))

[[ 0.6 -0.2]
 [-0.2  0.4]]


In [ ]:
A = np.array([[2,1],[1,3]])
B = np.array([[100],[120]])
print(np.linalg.solve(A,B))

[[36.]
 [28.]]


In [ ]:
def charge(t):
  return 100 - 2*t - 0.5*t**2
def rate_of_change(t):
  return -2 - t
t1 = 2
t2 = 5
rate1 = rate_of_change(t1)
rate2 = rate_of_change(t2)
print("Rate of change: dC/dt = -2 - t")
print(f"At t = {t1}, dC/dt = {rate1} percentage points/hour")
print(f"At t = {t2}, dC/dt = {rate2} percentage points/hour")
if rate2 < rate1:
  print("The battery is losing charge at an increasing rate.")
elif rate2 > rate1:
  print("The battery is losing charge at a decreasing rate.")
else:
  print("The battery is losing charge at a constant rate.")

Rate of change: dC/dt = -2 - t
At t = 2, dC/dt = -4 percentage points/hour
At t = 5, dC/dt = -7 percentage points/hour
The battery is losing charge at an increasing rate.
